name: Deploy Vite to Laravel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Copy files to Laravel public directory
        run: cd dashboard
          npm install
          npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4" # Laravel projenizin PHP s端r端m端n端 burada belirtin

      - name: Set up Composer
        run: sudo apt-get install composer

      - name: Install Laravel dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Run Laravel migrations
        run: php artisan migrate --force
